import styles from './article.module.css';
export const metadata={title:'What Is BaZi? A Beginner’s Guide — JIJI RULING'};
export default function Article(){return <main id="main-content" className={styles.page}><a className={styles.back} href="/learn#bazi">← Back To Learning Guides</a><header className={styles.header}><p className={styles.meta}>BAZI FOUNDATIONS · 5 MIN READ · BEGINNER</p><h1>What Is BaZi?<br/><em>A Beginner’s Guide</em></h1><p className={styles.intro}>A simple introduction for Western beginners</p><p>Ba Zi (also known as Four Pillars of Destiny) is an ancient Chinese system to understand a person’s natural personality, potential, life trends and possible challenges. It comes from traditional Chinese astrology, not Western horoscope.</p></header>
<div className={styles.layout}><nav className={styles.contents} aria-label="In this guide"><span>IN THIS GUIDE</span><a href="#idea">The Core Idea</a><a href="#elements">The Building Blocks</a><a href="#example">A Simple Example</a><a href="#limits">Possibilities & Limits</a><a href="#comparison">Western Astrology</a></nav><article className={styles.body}>
<section id="idea"><p className={styles.number}>01 / THE FOUNDATIONS</p><h2>The Core Idea</h2><p>When you were born, there was a unique energy pattern in the universe. This pattern is recorded by 8 Chinese characters, so we call it Ba Zi.</p><div className={styles.definition}><span>八 <small>Ba = Eight</small></span><span>字 <small>Zi = Character</small></span></div><p>These 8 characters are split into Four Pillars, one pillar for each part of your birth information:</p><ol className={styles.pillars}>{[['Year','The year you were born'],['Month','The month you were born'],['Day','The day you were born'],['Hour','The exact hour you were born']].map(([name,desc])=><li key={name}><h3>{name} Pillar</h3><div aria-hidden="true"><i/><i/></div><p>{desc}</p></li>)}</ol><p className={styles.formula}>2 Characters Per Pillar <span>×</span> 4 Pillars <span>=</span> 8 Characters</p></section>
<section id="elements"><p className={styles.number}>02 / THE LANGUAGE OF A CHART</p><h2>The Building Blocks</h2><h3>10 Heavenly Stems & 12 Earthly Branches</h3><p>The 8 characters are picked from two sets of symbols. Every symbol links to one of the Five Elements: Wood, Fire, Earth, Metal, Water.</p><p>The Five Elements represent different types of energy:</p><dl className={styles.elements}>{[['Wood','木','Growth, creativity, kindness, flexibility','Like trees'],['Fire','火','Passion, energy, communication, leadership','Like flame'],['Earth','土','Stability, care, trust, practicality','Like soil'],['Metal','金','Logic, discipline, fairness, strength','Like metal'],['Water','水','Wisdom, intuition, adaptability, ideas','Like river']].map(([name,cn,desc,example])=><div key={name}><dt><span aria-hidden="true">{cn}</span>{name}</dt><dd>{desc}<small>{example}</small></dd></div>)}</dl><p>The elements interact with each other. Some elements support each other; some restrict each other. This balance is the key of Ba Zi reading.</p></section>
<section id="example"><p className={styles.number}>03 / PUTTING IT TOGETHER</p><h2>Simple Example</h2><p>Suppose someone’s Day Master (the most important character in Ba Zi, it stands for you) is Wood.</p><div className={styles.examples}><div><h3>Water Feeds Wood</h3><p>If this person has strong Water in their chart: Water feeds Wood. This person is usually thoughtful, creative, gets support easily.</p></div><div><h3>Metal Cuts Wood</h3><p>If this person has too much Metal: Metal cuts Wood. They may face more pressure, criticism, or feel restricted often.</p></div></div><p>The Day Master is the center of your Ba Zi. All other 7 characters describe the people, events and energy around you.</p></section>
<section id="limits"><p className={styles.number}>04 / KEEPING PERSPECTIVE</p><h2>What Ba Zi Can & Cannot Do</h2><div className={styles.limits}><div><h3>What It Offers</h3><p>It tells your natural strengths and weaknesses, suitable career directions, periods of good or tough luck.</p><p>Example: A strong Fire Day Master often does well in jobs needing public speaking, sales or creative work.</p></div><div><h3>What It Cannot Promise</h3><p>It cannot predict exact fixed events like “you will get married on 10th October” or “you will definitely become rich”.</p><p>Ba Zi shows energy trends. Your own choices still change your life.</p></div></div></section>
<section id="comparison"><p className={styles.number}>05 / TWO DIFFERENT SYSTEMS</p><h2>Quick Comparison With Western Astrology</h2><div className={styles.comparison}><div><h3>Western Astrology</h3><p>Uses planets and star constellations.</p></div><div><h3>Ba Zi</h3><p>Uses Chinese calendar, time and Five Elements energy.</p></div></div><p>Both study birth time, but they use completely different systems.</p></section>
<aside className={styles.important}><h2>Important Note</h2><p>Ba Zi is a traditional Chinese philosophy tool. It is not modern science. Treat it as a way for self-reflection, not absolute truth.</p></aside><div className={styles.end}><a href="/learn#bazi">← Continue Learning</a><a href="/free-bazi">Explore Your BaZi Chart ↗</a></div>
</article></div></main>}
