import styles from './article.module.css';
export const metadata={title:'What Is BaZi? A Beginner’s Guide — JIJI RULING'};

const elementPaths = {
 Wood: 'M12 3a4 4 0 0 0-4 4 4.5 4.5 0 0 0-1 9h10a4.5 4.5 0 0 0-1-9 4 4 0 0 0-4-4ZM12 10v11m-3 0h6m-3-7-3-3m3 5 3-3',
 Fire: 'M13 2c1 5-4 7-4 10-1-1-2-2-2-4-2 3-3 5-3 8a8 8 0 0 0 16 0c0-5-4-10-7-14ZM12 13c0 3-3 4-3 6a3 3 0 0 0 6 0c0-2-2-4-3-6Z',
 Earth: 'm3 17 6-9 4 6 3-4 5 7M3 21h18M7 17h7',
 Metal: 'm8 4-5 6 9 11 9-11-5-6ZM3 10h18M8 4l4 17 4-17',
 Water: 'M3 7c3-4 6 4 9 0s6 4 9 0M3 12c3-4 6 4 9 0s6 4 9 0M3 17c3-4 6 4 9 0s6 4 9 0',
};
export default function Article(){return <main id="main-content" className={styles.page}><a className={styles.back} href="/learn#bazi">←︎ Back To Learning Guides</a><header className={styles.header}><p className={styles.meta}>BAZI FOUNDATIONS · 5 MIN READ · BEGINNER</p><h1>What Is BaZi?<br/><em>A Beginner’s Guide</em></h1><p className={styles.intro}>A simple introduction for Western beginners</p><p>Ba Zi (also known as Four Pillars of Destiny) is an ancient Chinese system to understand a person’s natural personality, potential, life trends and possible challenges. It comes from traditional Chinese astrology, not Western horoscope.</p></header>
<div className={styles.layout}><nav className={styles.contents} aria-label="In this guide"><span>IN THIS GUIDE</span><a href="#idea">The Core Idea</a><a href="#elements">The Building Blocks</a><a href="#example">A Simple Example</a><a href="#limits">Possibilities & Limits</a><a href="#comparison">Western Astrology</a></nav><article className={styles.body}>
<section id="idea"><p className={styles.number}>01 / THE FOUNDATIONS</p><h2>The Core Idea</h2><p>When you were born, there was a unique energy pattern in the universe. This pattern is recorded by 8 Chinese characters, so we call it Ba Zi.</p><div className={styles.definition}><span>八 <small>Ba = Eight</small></span><span>字 <small>Zi = Character</small></span></div><p>These 8 characters are split into Four Pillars, one pillar for each part of your birth information:</p><ol className={styles.pillars}>{[['Year','The year you were born','甲','Jia','子','Zi','甲子年'],['Month','The month you were born','丙','Bing','寅','Yin','丙寅月'],['Day','The day you were born','戊','Wu','辰','Chen','戊辰日'],['Hour','The exact hour you were born','壬','Ren','戌','Xu','壬戌时']].map(([name,desc,stem,stemPinyin,branch,branchPinyin,label])=><li key={name}><h3>{name} Pillar</h3><div className={styles.pillarCharacters}><span><b lang="zh">{stem}</b><small>{stemPinyin}</small></span><span><b lang="zh">{branch}</b><small>{branchPinyin}</small></span></div><p className={styles.pillarLabel} lang="zh">{label}</p><p>{desc}</p></li>)}</ol><p className={styles.formula}>2 Characters Per Pillar <span>×</span> 4 Pillars <span>=</span> 8 Characters</p></section>
<section id="elements"><p className={styles.number}>02 / THE LANGUAGE OF A CHART</p><h2>The Building Blocks</h2><h3>10 Heavenly Stems & 12 Earthly Branches</h3><p>The 8 characters are picked from two sets of symbols. Every symbol links to one of the Five Elements: Wood, Fire, Earth, Metal, Water.</p><p>The Five Elements represent different types of energy:</p><dl className={styles.elements}>{[['Wood','木','Growth, creativity, kindness, flexibility','Like trees'],['Fire','火','Passion, energy, communication, leadership','Like flame'],['Earth','土','Stability, care, trust, practicality','Like soil'],['Metal','金','Logic, discipline, fairness, strength','Like metal'],['Water','水','Wisdom, intuition, adaptability, ideas','Like river']].map(([name,cn,desc,example])=><div key={name}><dt><svg className={styles.elementIcon} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={elementPaths[name]}/></svg>{name}</dt><dd>{desc}<small>{example}</small></dd></div>)}</dl><p>The elements interact with each other. Some elements support each other; some restrict each other. This balance is the key of Ba Zi reading.</p></section>
<section id="example"><p className={styles.number}>03 / PUTTING IT TOGETHER</p><h2>Simple Example</h2><p>Suppose someone’s Day Master (the most important character in Ba Zi, it stands for you) is Wood.</p><div className={styles.examples}><div><h3>Water Feeds Wood</h3><p>If this person has strong Water in their chart: Water feeds Wood. This person is usually thoughtful, creative, gets support easily.</p></div><div><h3>Metal Cuts Wood</h3><p>If this person has too much Metal: Metal cuts Wood. They may face more pressure, criticism, or feel restricted often.</p></div></div><p>The Day Master is the center of your Ba Zi. All other 7 characters describe the people, events and energy around you.</p></section>
<section id="limits"><p className={styles.number}>04 / KEEPING PERSPECTIVE</p><h2>What Ba Zi Can & Cannot Do</h2><div className={styles.limits}><div><h3>What It Offers</h3><p>It tells your natural strengths and weaknesses, suitable career directions, periods of good or tough luck.</p><p>Example: A strong Fire Day Master often does well in jobs needing public speaking, sales or creative work.</p></div><div><h3>What It Cannot Promise</h3><p>It cannot predict exact fixed events like “you will get married on 10th October” or “you will definitely become rich”.</p><p>Ba Zi shows energy trends. Your own choices still change your life.</p></div></div></section>
<section id="comparison"><p className={styles.number}>05 / TWO DIFFERENT SYSTEMS</p><h2>Quick Comparison With Western Astrology</h2><div className={styles.comparison}><div><h3>Western Astrology</h3><p>Uses planets and star constellations.</p></div><div><h3>Ba Zi</h3><p>Uses Chinese calendar, time and Five Elements energy.</p></div></div><p>Both study birth time, but they use completely different systems.</p></section>
<aside className={styles.important}><h2>Important Note</h2><p>Ba Zi is a traditional Chinese philosophy tool. It is not modern science. Treat it as a way for self-reflection, not absolute truth.</p></aside><div className={styles.end}><a href="/learn#bazi">←︎ Continue Learning</a><a className={styles.chartCta} href="/free-bazi">Explore Your BaZi Chart <span aria-hidden="true">↗︎</span></a></div>
</article></div></main>}
