'use client';
import {useEffect,useRef,useState} from 'react';
import styles from './space.module.css';
function Files({files,onRemove}){
 const [urls,setUrls]=useState([]);
 useEffect(()=>{const next=files.map(f=>f.type.startsWith('image/')?URL.createObjectURL(f):null);setUrls(next);return()=>next.forEach(u=>{if(u)URL.revokeObjectURL(u);});},[files]);
 return <div className={styles.files}>{files.map((file,i)=><div key={file.name+i}>{urls[i]?<img src={urls[i]} alt={`Selected file ${i+1}`}/>:<span className={styles.pdf}>PDF floor plan</span>}<span>{file.name}</span><button type="button" onClick={()=>onRemove(i)} aria-label={`Remove ${file.name}`}>Remove</button></div>)}</div>;
}
export default function SpacePreview(){
 const [photos,setPhotos]=useState([]),[plans,setPlans]=useState([]),[error,setError]=useState(''),[ready,setReady]=useState(false);
 const dialog=useRef(null);
 function choose(event,plan=false){
  const incoming=Array.from(event.target.files||[]);event.target.value='';if(!incoming.length)return;
  setReady(false);setError('');
  const allowed=plan?['image/jpeg','image/png','image/webp','application/pdf']:['image/jpeg','image/png','image/webp'];
  if(incoming.some(f=>!allowed.includes(f.type)||f.size>10*1024*1024)){setError('Please choose JPG, PNG or WebP files up to 10 MB each. A floor plan may also be a PDF.');return;}
  if(plan){if(incoming.length!==1){setError('Choose one floor plan.');return;}setPlans(incoming);}
  else{if(photos.length+incoming.length>4){setError('Choose no more than four room photos. Remove a photo to replace it.');return;}setPhotos([...photos,...incoming]);}
 }
 function review(event){event.preventDefault();setError('');if(photos.length<2||photos.length>4){setError('Please add 2–4 room photos.');return;}if(plans.length!==1){setError('Please add one simple floor plan.');return;}setReady(true);dialog.current.showModal();}
 return <main id="main-content" className={styles.page}><p className={styles.preview}>DESIGN PREVIEW · Files stay in your browser · No payment or upload</p>
 <section className={styles.hero}><div><p className="eyebrow">Feng Shui / Single-space layout audit</p><h1>Understand<br/><em>Your Space</em></h1><p className={styles.intro}>A more considered room.<br/>A better everyday rhythm.</p><p>A focused review of one room — its furniture placement, movement, light and everyday use — through a traditional Feng Shui lens.</p><a href="#space-form" className={styles.button}>Start with your space ↘</a></div><div className={styles.room}><img src="/space-courtyard.webp" alt="A tranquil tea room overlooking a traditional courtyard garden" width="1101" height="726"/><span>ONE ROOM. THOUGHTFULLY ARRANGED.</span></div></section>
 <section className={styles.includes}><div><p className="eyebrow">One space, a clear starting point</p><h2>Small changes.<br/>Practical direction.</h2></div><ul><li><strong>Layout & flow</strong><span>Furniture positioning and clear routes through your room.</span></li><li><strong>Comfort & balance</strong><span>Light, visual clutter and how the space supports its purpose.</span></li><li><strong>A focused action list</strong><span>Prioritized suggestions for one room, with changes you can consider at your own pace.</span></li></ul></section>
 <section id="space-form" className={styles.formSection}><p className="eyebrow">Tell us about your room</p><h2>Your space, in a little more detail.</h2><form onSubmit={review} onChange={()=>setReady(false)}><div className={styles.grid}><div className={styles.fields}>
 <label>01 / Space type<select required defaultValue="" name="spaceType"><option value="" disabled>Select your space</option><option>Bedroom</option><option>Living room</option><option>Office</option><option>Other</option></select></label>
 <label>02 / What is this room used for?<textarea required minLength={5} maxLength={2000} name="purpose" rows={4} placeholder="Describe how you use the room, who uses it and what you would like to improve."/></label>
 <fieldset><legend>03 / Room photos <span>2–4 photos</span></legend><p>Show the room from different corners, including the entrance and main furniture. Avoid showing people, personal documents or identifying details.</p><label className={styles.upload}>Choose room photos<input aria-label="Room photos" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>choose(e)}/></label><p className={styles.note}>JPG, PNG or WebP · Up to 10 MB each · {photos.length}/4 selected</p><Files files={photos} onRemove={i=>{setPhotos(photos.filter((_,n)=>n!==i));setReady(false);}}/></fieldset>
 <fieldset><legend>04 / Simple floor plan <span>1 file</span></legend><p>A hand-drawn sketch is welcome. Mark doors, windows and main furniture; add approximate dimensions and north if known.</p><label className={styles.upload}>Choose floor plan<input aria-label="Floor plan" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>choose(e,true)}/></label><p className={styles.note}>JPG, PNG, WebP or PDF · Up to 10 MB</p><Files files={plans} onRemove={()=>{setPlans([]);setReady(false);}}/></fieldset>
 </div><aside className={styles.summary}><p className="eyebrow">Single-space audit</p><h3>Understand Your Space</h3><p className={styles.price}>$49.99 <small>USD</small></p><p>One bedroom, living room, office or another single room.</p><ul><li>Review of your room photos and sketch</li><li>Practical layout observations</li><li>A written set of suggested adjustments</li></ul><p className={styles.note}>This is a room-layout review, not a whole-property or time-based Feng Shui analysis. No health, wealth or other outcomes are guaranteed.</p><button className={styles.button} type="submit">Review my details ↗</button><p className={styles.note}>Preview only. Checkout and delivery timing are not yet configured. No files are sent or saved by the site.</p>{error&&<p role="alert" className={styles.error}>{error}</p>}{ready&&<p role="status">Preview details complete. Nothing has been submitted.</p>}</aside></div></form></section>
 <section className={styles.faq}><h2>A simple way to begin.</h2><details><summary>Do I need a professional floor plan?</summary><p>No. A readable hand-drawn sketch is enough for the planned layout review. Show the room outline, entrance, windows and main furniture.</p></details><details><summary>Does this cover my whole home?</summary><p>The $49.99 price covers one room. Choose the single space you most want to focus on.</p></details><details><summary>What happens after I add my files?</summary><p>In this preview, you can review your selected materials. They remain in this browser page and are cleared when it is refreshed or closed. The upload, payment and report delivery service is not connected yet.</p></details></section>
 <dialog ref={dialog} className={styles.dialog} aria-labelledby="space-review-title"><h2 id="space-review-title">Your preview is ready.</h2><p>You have selected {photos.length} room photos and one floor plan. No files have been uploaded, no analysis has been performed and no payment has been taken.</p><form method="dialog"><button className={styles.button}>Back to my space</button></form></dialog></main>;
}
