import React from "react";
import styles from './learn.module.css';
export const metadata = { title: 'Learn — JIJI RULING', robots: { index: false, follow: false } };
const paths = [
 {id:'bazi',name:'BaZi & The Five Elements',number:'01',intro:'Begin with yourself',description:'Learn the language of a birth chart, one idea at a time.',lessons:[
 ['What Is BaZi? A Beginner’s Guide','BaZi foundations','5','Meet the Four Pillars and discover how a chart becomes a starting point for reflection.','A BaZi chart organizes the year, month, day and hour of birth into four pairs of characters. Start by noticing the structure, rather than looking for a verdict about your future.','Notice one pattern in your daily habits that you would like to understand better.'],
 ['The Five Elements Explained With Everyday Examples','Five Elements','6','Explore Wood, Fire, Earth, Metal and Water through familiar patterns of everyday life.','Think of the elements as a traditional language for qualities and change. Growth, warmth, steadiness, refinement and adaptability offer useful starting images, rather than fixed labels for a person.','Where do you need more room to grow, and where would a little structure help?'],
 ['What Does Your Birth Time Mean In BaZi?','Your birth chart','4','Understand the Hour Pillar and why uncertainty deserves an honest place in your chart.','Birth time helps determine the Hour Pillar. Local time, historical time zones and daylight-saving changes matter when calculating a chart. If your time is unknown, a partial chart is more honest than an invented time.','Check whether your recorded birth time comes from a document or a family estimate.'] ]},
 {id:'space',name:'Feng Shui & Your Space',number:'02',intro:'Look at your surroundings',description:'Bring a more thoughtful eye to the rooms you use every day.',lessons:[
 ['What Is Feng Shui? A Practical Introduction','Feng Shui foundations','5','Begin with the relationship between a room, its arrangement and the way you use it.','For this guide, begin with observable features: doors, windows, furniture, light and movement. Traditional Feng Shui provides a cultural lens; it does not guarantee health, wealth or other outcomes.','Choose one room and describe what you want to do and feel there.'],
 ['How To Look At The Flow Of A Room','Room flow','4','Follow an everyday route and notice what makes movement feel easy or awkward.','Walk from the entrance to the places you use most. Notice narrow passages, furniture you have to avoid and surfaces that collect things. Start with practical access and comfort.','Trace your most frequent route through the room on a simple sketch.'],
 ['Five Simple Feng Shui Ideas For Your Home','Everyday practice','6','Small, considered adjustments to try before making a bigger change.','Clear a frequently used route, make a task area easier to use, review the lighting, give everyday objects a home and create a quiet resting spot. Try one change at a time and observe your experience.','What is one reversible change you could make this weekend?'] ]},
 {id:'connections',name:'I Ching & Relationships',number:'03',intro:'Make room for another perspective',description:'Explore change, balance and the ways we relate to one another.',lessons:[
 ['What Is The I Ching?','I Ching foundations','6','An introduction to the Book of Changes and a tradition of thinking about change.','The I Ching is a Chinese classic organized around hexagrams. Approach it here as a cultural and reflective text: a way to consider a situation from different angles, rather than a source of certain predictions.','What part of a current situation is changing, and what remains steady?'],
 ['Yin And Yang In Everyday Life','Yin & Yang','4','Consider complementary qualities without sorting people into rigid categories.','Activity and rest, speaking and listening, planning and responding can offer everyday starting points for understanding complementary qualities. Context matters; neither side is inherently better.','Where might listening be more useful than another explanation?'],
 ['How To Think About Compatibility Beyond “A Perfect Match”','Relationship insight','7','Explore differences with partners, family, friends and colleagues through better questions.','A relationship cannot be reduced to a score. Shared expectations, communication and circumstances matter. Use a symbolic reading to open a conversation, never to decide another person’s worth or your future together.','Ask each other: what helps you feel understood when we disagree?'] ]}
];
function Diagram({kind}) {return <div className={`${styles.diagram} ${styles[kind]}`} aria-hidden="true">{kind==='bazi'?<><i/><i/><i/><i/><i/></>:kind==='space'?<><i/><i/><i/></>:<><i/><i/></>}</div>}
export default function Learn(){return <main id="main-content" className={styles.page}>
 <header className={styles.hero}><div><p className={styles.kicker}>THE JIJI RULING LEARNING GUIDE</p><h1>A Little Wisdom<br/><em>For Everyday Life</em></h1><p className={styles.lede}>A gentle introduction to BaZi, your surroundings and the connections that shape your days.</p><a className={styles.start} href="#bazi">Start With The Foundations <span aria-hidden="true">↘</span></a></div><aside className={styles.fieldNotes}><p className={styles.kicker}>A FIELD GUIDE TO</p><div className={styles.elementStrip}>{['Wood','Fire','Earth','Metal','Water'].map((x,i)=><div key={x}><span>{['木','火','土','金','水'][i]}</span><small>{x}</small></div>)}</div><p>Notice. Reflect. Explore.</p><span>Ancient ideas, approached with curiosity.</span></aside></header>
 <nav className={styles.paths} aria-label="Learning paths"><span>CHOOSE YOUR PATH</span>{paths.map(p=><a key={p.id} href={'#'+p.id}><small>{p.number}</small>{p.name}<span aria-hidden="true">↓</span></a>)}</nav>
 <div className={styles.note}><span>START ANYWHERE · GO AT YOUR OWN PACE</span><p>9 beginner guides · No prior knowledge needed</p><small>Preview edition · Reading times are estimates for the planned full guides. Open a card for a short introduction.</small></div>
 {paths.map(p=><section key={p.id} id={p.id} className={styles.path}><div className={styles.pathIntro}><span className={styles.pathNumber}>{p.number} / LEARNING PATH</span><h2>{p.name}</h2><p>{p.description}</p>{p.id==='space'?<figure className={styles.photo}><img src="/space-courtyard.webp" width="1101" height="726" alt="A tea room opening onto a peaceful courtyard" loading="lazy"/><figcaption>Begin with the space around you</figcaption></figure>:<Diagram kind={p.id}/>}</div><div className={styles.lessons}>{p.lessons.map(([title,topic,time,desc,body,prompt],i)=><React.Fragment key={title}>{p.id === "bazi" ? <article className={styles.lesson}><a className={styles.articleLink} href={["/learn/what-is-bazi", "/learn/five-elements", "/learn/birth-time"][i]}><div className={styles.meta}><span>{topic}</span><span>{time} min read · Beginner</span></div><div className={styles.lessonTitle}><span className={styles.order}>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><span aria-hidden="true">↗</span></div><p>{desc}</p><span className={styles.openLabel}>Explore This Guide</span></a></article> : <details className={styles.lesson}><summary><div className={styles.meta}><span>{topic}</span><span>{time} min read · Beginner</span></div><div className={styles.lessonTitle}><span className={styles.order}>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><span className={styles.plus} aria-hidden="true">+</span></div><p>{desc}</p><span className={styles.openLabel}>Explore This Guide</span></summary><div className={styles.excerpt}><span className={styles.kicker}>GUIDE PREVIEW</span><p>{body}</p><div><strong>A Moment To Reflect</strong><p>{prompt}</p></div></div></details>}</React.Fragment>)}</div></section>)}
 <section className={styles.closing}><span className={styles.kicker}>FROM UNDERSTANDING TO REFLECTION</span><h2>Get To Know Your Own Chart</h2><p>Bring a little context to your first reading with our free BaZi calculator.</p><a className={styles.start} href="/free-bazi">Explore My Chart <span aria-hidden="true">↗</span></a></section>
 <p className={styles.disclaimer}>These guides explore traditional cultural ideas for learning and reflection. They are not scientific assessments or predictions.</p>
 </main>}
