'use client';
import { useState, useRef } from 'react';
import styles from './relationship.module.css';
import BirthPicker from '../free-bazi/birth-picker';

function Person({number}) {
 const [unknown,setUnknown]=useState(false);
 const [birthDate,setBirthDate]=useState(''),[birthTime,setBirthTime]=useState(''),[picker,setPicker]=useState(null);
 return <fieldset className={styles.person}><legend>Person {number}</legend>{picker&&<BirthPicker kind={picker} value={picker==='date'?birthDate:birthTime} onCancel={()=>setPicker(null)} onConfirm={value=>{if(picker==='date')setBirthDate(value);else setBirthTime(value);setPicker(null);}}/>}<label>Name <span>(optional)</span><input name={'name'+number} autoComplete="off" placeholder={number===1?'Your name':'Their name'}/></label><div className={styles.pickerField}><span id={'date-label-'+number}>Birth date</span><button className={styles.pickerTrigger} type="button" aria-haspopup="dialog" aria-labelledby={'date-label-'+number+' date-value-'+number} onClick={()=>setPicker('date')}><span id={'date-value-'+number}>{birthDate||'Select year / month / day'}</span><span aria-hidden="true">⌄</span></button></div><label className={styles.checkbox}><input type="checkbox" checked={unknown} onChange={e=>{setUnknown(e.target.checked);setBirthTime('');}}/>Birth time unknown</label><div className={styles.pickerField}><span id={'time-label-'+number}>Birth time</span><button className={styles.pickerTrigger} type="button" aria-haspopup="dialog" disabled={unknown} aria-labelledby={'time-label-'+number+' time-value-'+number} onClick={()=>setPicker('time')}><span id={'time-value-'+number}>{unknown?'Unknown':birthTime||'Select hour / minute'}</span><span aria-hidden="true">⌄</span></button></div><label>Birth city <input name={'city'+number} autoComplete="off" placeholder="City, region, country"/></label><p className={styles.note}>Preview field only. Location search is not connected. Unknown birth times will not be treated as midnight.</p></fieldset>;
}
export default function RelationshipPreview(){
 const [show,setShow]=useState(false);
 const result=useRef(null);
 function preview(event){event.preventDefault();setShow(true);requestAnimationFrame(()=>{result.current?.scrollIntoView({behavior:'auto',block:'start'});result.current?.focus();});}
 return <main id="main-content" className={styles.page}>
 <div className={styles.preview}>DESIGN PREVIEW · No live calculation or payment · Entries stay on this page</div>
 <section className={styles.hero}><div><p className="eyebrow">Compatibility / Relationship Insight</p><h1>Understand Your<br/><em>Relationships</em></h1><p>Explore how you communicate, support one another and navigate differences through the lens of BaZi.</p><p className={styles.scope}>For romantic partners, family members, friends, colleagues and business partners.</p><a className={styles.primary} href="#relationship-form">Explore your connection <span aria-hidden="true">↘</span></a></div><div className={styles.harmonyArt}><img src="/relationship-harmony.webp" width="1024" height="1536" alt="Two paths, one higher harmony. Different strengths, perspectives and uniqueness come together for a more complete story." /></div></section>
 <section id="relationship-form" className={styles.formSection}><p className="eyebrow">01 / Start with two perspectives</p><h2>Your Relationship, In Context</h2><p>Use fictional details to explore this preview; no information is required to view the sample.</p><form onSubmit={preview}><div className={styles.people}><Person number={1}/><Person number={2}/></div><p className={styles.note}>For adults aged 18+. Only provide another person’s birth information with their permission. This prototype does not submit, store or calculate from your entries.</p><button className={styles.primary} type="submit">View sample relationship insight <span aria-hidden="true">↗</span></button></form></section>
 {show&&<section ref={result} tabIndex={-1} className={styles.result} aria-label="Sample relationship insight"><p className="eyebrow">02 / Sample only</p><h2>Begin With A Better Question</h2><p>These are general conversation prompts, not findings from your birth details. No charts have been compared.</p><div className={styles.insights}><article><span>01</span><h3>How You Connect</h3><p>What helps each of you feel understood and supported in this relationship?</p></article><article><span>02</span><h3>Where Differences Surface</h3><p>When your preferences differ, what helps each person feel heard before a decision is made?</p></article><article><span>03</span><h3>What You Can Try</h3><p>Choose one expectation you have not discussed. Take turns explaining what it means to you, without trying to solve it immediately.</p></article></div><p className={styles.note}>A future chart-based reading would distinguish calculated observations from interpretation, and acknowledge missing birth times.</p></section>}
 <section className={styles.paid}><div><p className="eyebrow">A deeper, human perspective</p><h2>Relationship Insight</h2><p>A planned human-written report for the relationship you want to understand — with attention to communication, support, boundaries and collaboration.</p></div><div><p className={styles.price}>$39.99 <span>/ two-person report</span></p><ul><li>Two individual charts considered together</li><li>Interpretation tailored to your relationship type</li><li>Practical prompts for shared reflection</li></ul><p className={styles.note}>Coming soon · Checkout is not available. Delivery details will be confirmed before purchase.</p></div></section>
 <section className={styles.faq}><h2>A Few Things To Know</h2><details><summary>Is this only for couples?</summary><p>No. Choose family, friendship, colleagues or business partners to focus on the kind of connection you want to explore. Romantic assumptions do not belong in every relationship.</p></details><details><summary>Does this decide whether we are compatible?</summary><p>No. BaZi is a traditional cultural framework, not a validated measure of relationship success. Your choices, circumstances and communication matter.</p></details><details><summary>What if one of us does not know our birth time?</summary><p>The intended calculation will omit unknown hour pillars and explain the limits. This design preview does not calculate charts.</p></details><details><summary>Can I see my own chart first?</summary><p><a href="/free-bazi">Open the Free BaZi Calculator ↗</a></p></details></section>
 </main>;
}
