import { useRef } from 'react';
import styles from './report.module.css';
import { reflectionContent, elementShares, zodiacLabel } from './report-content.mjs';

const colors=['#5f7656','#a65d46','#9c7b43','#787571','#5b7c8e'];
const names=['Wood','Fire','Earth','Metal','Water'];
const chinese=['木','火','土','金','水'];
export default function Report({result,details,onEdit}) {
  const {chart,explanation}=result;
  const reading=reflectionContent(explanation);
  const {shares,total}=elementShares(chart.elements);
  const dialog=useRef(null);
  let end=0;
  const gradient=shares.map((s,i)=>{const start=end;end+=s.percent;return `${colors[i]} ${start}% ${end}%`;}).join(',');
  const year=chart.pillars.find(p=>p.key==='year');
  return <article className={styles.report} aria-label="Your BaZi Chart & Reading">
    <header className={styles.hero}><p className="eyebrow">Your free reading</p><div className={styles.titleRow}><h2>{details.name?.trim()?`${details.name.trim()}’s`:'Your'}<br/>BaZi Chart &amp; Reading</h2><img className={styles.emblem} src="/images/report/ceramic-emblem.webp" alt="" width="804" height="782" /></div><p>Your birth chart, a first interpretation, and a starting point for deeper self-understanding.</p></header>
    <section className={styles.overview} aria-label="Your chart overview"><p className="eyebrow">01 / Your chart overview</p><dl className={styles.details}><div><dt>Name</dt><dd>{details.name?.trim()||'Not provided'}</dd></div><div><dt>Birth date</dt><dd>{details.birthDate}</dd></div><div><dt>Birth time</dt><dd>{details.unknown?'Unknown · hour omitted':details.birthTime}</dd></div><div><dt>Birthplace</dt><dd>{details.city}</dd></div></dl><p className={styles.note}>Birth time zone (IANA): {chart.timeZone} · {details.unknown?'Possible UTC offsets on birth date':'UTC offset at birth'}: {chart.utcOffsets.map(offset=>`UTC${offset}`).join(' / ')}</p>{details.unknown&&chart.utcOffsets.length>1&&<p className={styles.note}>The clocks changed on this date; both are shown because the birth time is unknown.</p>}<button type="button" className={styles.edit} onClick={onEdit}>Edit birth details</button></section>
    <section className={styles.section} aria-labelledby="bazi-chart-title"><p className="eyebrow">02 / Your BaZi chart</p><div className={styles.chartHead}><div className={styles.pillarHeading}><h3 id="bazi-chart-title">Your Four Pillars</h3><img className={styles.pillarLettering} src="/images/report/four-pillars.webp" alt="四柱" width="801" height="516" /></div><span className={styles.badge}>Chinese zodiac · {zodiacLabel(year?.branch)}</span></div>
      {chart.warnings.length>0&&<aside className={styles.notice} aria-label="Calculation limitations"><ul>{chart.warnings.map(w=><li key={w}>{w}</li>)}</ul></aside>}
      <div className={styles.tableFrame}><table className={styles.table} aria-label="Calculated Four Pillars"><thead><tr>{chart.pillars.map(p=><th scope="col" key={p.key} className={p.key==='day'?styles.day:undefined}>{p.label}{p.key==='day'?' · You':''}</th>)}</tr></thead><tbody>{['stem','branch'].map(type=><tr key={type}>{chart.pillars.map(p=><td key={p.key} className={p.key==='day'?styles.day:undefined}><strong style={{color:colors[names.indexOf(p[`${type}Element`])]}}>{p[type]??'—'}</strong><span>{p[type]?p[`${type}Element`]:'Omitted'}</span><small>{type==='stem'?'Heavenly stem':'Earthly branch'}</small></td>)}</tr>)}</tbody></table><div className={styles.chartFoot}>Day Master &nbsp; <b>{chart.dayMaster.stem} · {chart.dayMaster.polarity} {chart.dayMaster.element}</b><span>{chart.complete?'Four pillars · Eight characters':'Partial chart · available pillars only'}</span></div></div>
      <div className={styles.elements}><div className={styles.elementHeading}><h4>Your Five Elements</h4><img className={styles.elementLettering} src="/images/report/five-elements.webp" alt="五行" width="1103" height="648" /></div><p className={styles.note}>Main-element distribution across your {chart.complete?'Four Pillars':'available pillars'}</p><div className={styles.chart}><div className={styles.donut} style={{background:total?`conic-gradient(${gradient})`:'var(--line)'}} aria-hidden="true"><div><strong>{total}</strong><small>Chart characters</small></div></div><dl className={styles.legend}>{shares.map((s,i)=><div key={s.name}><dt><i style={{background:colors[i]}}/>{s.name} · {chinese[i]}</dt><dd>{Number(s.percent.toFixed(1))}% <small>({s.count}/{total})</small></dd></div>)}</dl></div><p className={styles.note}>Main-element quantity shares, not five-element strength scores. Hidden stems and seasonal weighting are not included. Zero does not mean an element is absent from the full chart. Rounded percentages may not add to exactly 100%.</p></div>
      <details className={styles.rules}><summary>How to read your chart &amp; calculation rules</summary><p>Each pillar pairs a heavenly stem with an earthly branch. Your day stem is your Day Master. The zodiac follows the calculated year branch and the BaZi solar-year boundary, not January 1.</p><ul><li>Calculated by a deterministic program, not AI.</li><li>Gregorian dates and historical local civil time, including daylight-saving rules; no true solar-time correction.</li><li>The day changes at local midnight. Solar terms set year and month boundaries, with a two-minute uncertainty guard.</li><li>Unknown birth times omit the hour pillar and uncertain seasonal pillars. Ambiguous or nonexistent times are not guessed.</li><li>Historical timezone data, especially before 1970, can be incomplete.</li><li>Rule version: {chart.rulesVersion}.</li></ul></details>
    </section>
    <section className={styles.reading} aria-labelledby="core-reading-title"><p className="eyebrow">03 / Your core reading</p><h3 id="core-reading-title">Your Core Reading</h3>{reading.personalized?<><p className={styles.summary}>{reading.summary}</p><p className={styles.note}>AI-assisted cultural interpretation. Treat these ideas as reflection prompts, not fixed truths or predictions.</p></>:<p>{reading.notice} No sample interpretation is presented as your personal reading.</p>}</section>
    <section className={styles.human} aria-labelledby="human-reading-title"><div><p className="eyebrow">Go deeper · A human perspective</p><h3 id="human-reading-title">Your Personal<br/>BaZi Blueprint</h3><p>Looking for the fuller picture? A planned paid report, analyzed and written by a human reader, and delivered to your email.</p></div><div><ul><li>A deeper interpretation of your full chart</li><li>Personal patterns, strengths and areas for reflection</li><li>Reflections on career, relationships and personal well-being</li><li>A considered written report you can revisit</li></ul><button type="button" onClick={()=>dialog.current?.showModal()}>Get My Personal BaZi Blueprint ↗</button><small>Coming soon · Not available to purchase</small></div></section>
    <dialog ref={dialog} className={styles.dialog} aria-labelledby="paid-reading-title"><h3 id="paid-reading-title">Your Personal BaZi Blueprint</h3><p>This human-written report will be delivered by email when purchasing becomes available. Pricing and delivery time will be shown before checkout.</p><p>Purchasing is not enabled. No payment is taken.</p><form method="dialog"><button>Back to my reading</button></form></dialog>
    <p className={styles.note}>For cultural education and personal reflection. BaZi is not scientifically validated and is not medical or other professional advice. Your optional name stays in the browser. The application does not persist birth submissions or reports. See our <a href="/privacy">Privacy Policy</a> for provider processing details.</p>
  </article>;
}
