import { useEffect, useRef } from 'react';
import styles from './report.module.css';
import { reflectionContent, elementShares } from './report-content.mjs';

const chapters=['Your Chart Overview','Your Core Pattern','Your Five Elements','How You Think','Your Natural Strengths','Your Blind Spots','How You Work','How You Connect','You Under Pressure','Your Personal Reflection Plan'];
const colors=['#72836a','#ba765e','#b59b69','#aaa6a0','#6e8a96'];
function Section({number,children}){return <section id={`blueprint-${number}`} className={styles.section}><p className="eyebrow">{String(number).padStart(2,'0')} · Personal BaZi Blueprint</p><h3>{chapters[number-1]}</h3>{children}</section>;}
function Pending({labels,notice}){return <><p className={styles.notice}>{notice}</p><dl className={styles.pending}>{labels.map(label=><div key={label}><dt>{label}</dt><dd>Personalized interpretation not available yet.</dd></div>)}</dl></>;}
function PaidLink({title,children}){return <details className={styles.rules}><summary>{title} ↗</summary><p>{children} This planned paid report is not available to purchase. No payment is taken.</p></details>;}
export default function Report({result,details,onEdit}){
  const {chart,explanation}=result;
  const reading=reflectionContent(explanation);
  const {shares,total,leaders}=elementShares(chart.elements);
  const menu=useRef(null),root=useRef(null);
  useEffect(()=>{
    const wide=window.matchMedia('(min-width:1100px)');
    const resize=()=>{if(menu.current)menu.current.open=wide.matches;};resize();wide.addEventListener('change',resize);
    const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)root.current?.querySelectorAll('nav a').forEach(link=>{if(link.hash==='#'+entry.target.id)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current');});},{rootMargin:'-10% 0px -65% 0px'});
    root.current?.querySelectorAll('section[id]').forEach(section=>observer.observe(section));
    return()=>{wide.removeEventListener('change',resize);observer.disconnect();};
  },[]);
  let end=0;const gradient=shares.map((s,i)=>{const start=end;end+=s.percent;return `${colors[i]} ${start}% ${end}%`;}).join(',');
  const notice=explanation.status==='disabled'?'Personalized AI interpretation is not enabled yet. Your calculated chart remains available.':'This part of your personalized interpretation is currently unavailable. Your calculated chart is unaffected.';
  return <article ref={root} className={styles.report} aria-label="Your Personal BaZi Blueprint">
    <header className={styles.hero}><p className="eyebrow">Your free reading</p><h2>{details.name?.trim()?`${details.name.trim()}’s Personal BaZi Blueprint`:'Your Personal BaZi Blueprint'}</h2><p>A starting point for reflection, grounded in your calculated chart.</p><span className={styles.badge}>{chart.complete?'Four pillars available':'Partial chart · uncertain pillars omitted'}</span></header>
    <div className={styles.blueprintLayout}><details ref={menu} className={styles.contents}><summary>Report contents</summary><nav aria-label="Report contents">{chapters.map((title,i)=><a href={`#blueprint-${i+1}`} key={title} onClick={()=>{if(window.innerWidth<1100)menu.current.open=false;}}><span>{String(i+1).padStart(2,'0')}</span> {title}</a>)}<a href="#blueprint-paid">Explore further ↗</a></nav></details><div className={styles.body}>
    <Section number={1}>
      <dl className={styles.details}><div><dt>Gregorian birth date</dt><dd>{details.birthDate}</dd></div><div><dt>Local birth time</dt><dd>{details.unknown?'Unknown · hour pillar omitted':details.birthTime}</dd></div><div><dt>Selected birth city</dt><dd>{details.city}</dd></div><div><dt>Birth time zone (IANA)</dt><dd>{chart.timeZone}</dd></div><div><dt>{details.unknown?'Possible UTC offsets on birth date':'UTC offset at birth'}</dt><dd>{chart.utcOffsets.map(offset=>`UTC${offset}`).join(' / ')}</dd></div></dl>
      <p className={styles.note}>Historical local clock rules include daylight-saving time where applicable.{details.unknown&&chart.utcOffsets.length>1?' The clocks changed on this date. Both possible offsets are shown because the birth time is unknown.':''}</p><button className={styles.edit} type="button" onClick={onEdit}>Edit birth details</button>
      {chart.warnings.length>0&&<aside className={styles.notice} aria-label="Calculation limitations"><strong>Before you read</strong><ul>{chart.warnings.map(w=><li key={w}>{w}</li>)}</ul></aside>}
      <details className={styles.rules}><summary>Chart details · Four Pillars &amp; calculation rules</summary><div className={styles.pillars}>{chart.pillars.map(p=><div key={p.key}><h4>{p.label}</h4><strong>{p.stem??'—'}{p.branch??'—'}</strong><p>{p.stem?`${p.stemElement} · ${p.branchElement}`:'Omitted'}</p></div>)}</div><ul><li>Gregorian dates and historical local civil time; no true solar-time correction.</li><li>The day changes at local midnight. Solar terms set year and month boundaries, with a two-minute uncertainty guard.</li><li>Unknown times omit the hour pillar and uncertain seasonal pillars. Ambiguous or nonexistent times are not guessed.</li><li>Historical timezone data, especially before 1970, can be incomplete.</li><li>Rule version: {chart.rulesVersion}.</li></ul></details>
    </Section>
    <Section number={2}>
      {reading.personalized?<><p className={styles.coreSummary}>{reading.summary}</p><p className={styles.note}>AI-assisted cultural interpretation; compare it with your experience.</p></>:<p className={styles.notice}>{notice} No personal summary has been invented in its place.</p>}
      <div className={styles.cards}><div><h4>Day Master</h4><p className={styles.metric}>{chart.dayMaster.stem} · {chart.dayMaster.polarity} {chart.dayMaster.element}</p><p className={styles.note}>The Heavenly Stem of your Day Pillar.</p></div><div><h4>Dominant Elements</h4><p className={styles.metric}>{leaders.join(' & ')||'Unavailable'}</p><p className={styles.note}>Highest main-element counts{leaders.length>1?' (tied)':''}, not weighted strength. {chart.complete?'':'Available pillars only.'}</p></div><div><h4>Core Archetype</h4><p>Not available yet.</p><p className={styles.note}>An interpretive label is not inferred from element counts alone.</p></div></div>
    </Section>
    <Section number={3}>
      <div className={styles.chart}><div className={styles.donut} style={{background:`conic-gradient(${gradient})`}} aria-hidden="true"><div><strong>五行</strong><small>Five Elements</small></div></div><dl className={styles.legend}>{shares.map((s,i)=><div key={s.name}><dt><i style={{background:colors[i]}}/>{s.name}</dt><dd>{Number(s.percent.toFixed(1))}% <small>({s.count}/{total})</small></dd></div>)}</dl></div>
      <p className={styles.note}>Main-element quantity shares in {chart.complete?'all four':'the available'} pillars. Not five-element strength scores. Rounded percentages may not add to exactly 100%.</p>
      <details className={styles.rules}><summary>How to read these percentages</summary><p>Each available pillar contributes one main stem element and one main branch element. Each percentage is its count divided by {total}, multiplied by 100. Hidden stems and seasonal weighting are not included. Zero does not mean an element is absent from every layer of the chart, or that you lack a personal quality.</p></details>
      <h4>What this may mean for you</h4><Pending notice="Element quantity alone cannot establish personality. The interpretation below is not enabled yet." labels={['Natural Strength','Potential Blind Spot','What Supports You']}/>
    </Section>
    <Section number={4}><p className={styles.subtitle}>How Your Mind Works</p><Pending notice={notice} labels={['How you process information','How you make decisions','How you respond to uncertainty','What happens when you overthink']}/><details className={styles.rules}><summary>Why BaZi says this</summary><p>No thinking-style interpretation has been generated. When available, its explanation must reference the actual calculated chart. Traditional associations are a cultural framework, not scientific proof of personality.</p></details></Section>
    <Section number={5}>{reading.personalized?<ol className={styles.strengths}>{reading.strengths.slice(0,3).map((s,i)=><li key={i}>{s}</li>)}</ol>:<p className={styles.notice}>{notice} Your top strengths will appear here when available.</p>}<p className={styles.note}>“How this shows up” and “When this strength becomes too much” require the expanded interpretation; those details are not available yet.</p></Section>
    <Section number={6}><p className={styles.notice}>{notice} No blind spots have been assigned.</p><p className={styles.note}>Each future entry will explain the pattern, possible reasoning, everyday examples, and a reflection question.</p></Section>
    <Section number={7}><Pending notice={notice} labels={['Your Working Style','Decision Style','Leadership','Independence vs Collaboration','Ideal Environment','What Drains You']}/><p>Want a deeper Career &amp; Wealth analysis?</p><a className={styles.textLink} href="#blueprint-career">Explore Career Blueprint ↗</a></Section>
    <Section number={8}><p className={styles.subtitle}>Your side of relationships</p><Pending notice={notice} labels={['How you open up','What makes you feel safe','How you communicate','How you handle conflict','What you may need from others']}/><p>Want to understand the dynamic between you and someone specific?</p><a className={styles.textLink} href="#blueprint-compatibility">Explore Relationship Compatibility ↗</a></Section>
    <Section number={9}><Pending notice={notice} labels={['When balanced','Under pressure','When depleted','Reset']}/></Section>
    <Section number={10}><p className={styles.subtitle}>What Do I Do With This?</p><Pending notice="A personalized action plan is not available yet." labels={['3 strengths to use more intentionally','3 patterns to watch']}/><h4>{reading.personalized?'Questions for reflection':'3 general reflection questions'}</h4>{!reading.personalized&&<p className={styles.note}>These questions are for everyone, not conclusions drawn from your chart.</p>}<ol>{reading.questions.map(q=><li key={q}>{q}</li>)}</ol><div className={styles.reflection}><h4>1 thing to experiment with this month</h4><p><strong>General exercise:</strong> choose one question above. Spend five minutes reflecting on it once a week, and notice whether your answer changes. Keep only what is useful to you.</p></div><p className={styles.note}>No answers are requested or collected.</p></Section>
    <section id="blueprint-paid" className={styles.next}><p className="eyebrow">Optional paid reports · Coming soon</p><h3>Continue at your own pace</h3><p>Your free blueprint ends here. These deeper reports are not available to purchase.</p><div id="blueprint-career"><PaidLink title="Explore Career Blueprint">A deeper Career &amp; Wealth reading.</PaidLink></div><div id="blueprint-compatibility"><PaidLink title="Explore Relationship Compatibility">A separate two-person reading.</PaidLink></div><div className={styles.reflection}><h4>Your Current Chapter</h4><span className={styles.badge}>Planned paid report · Not available</span><p>No current chapter or annual forecast has been calculated or included in this free report.</p><PaidLink title="Your Annual Forecast">A future time-based reading, pending a defined calculation method.</PaidLink></div></section>
    <p className={styles.note}>For cultural education and personal reflection. BaZi is not scientifically validated and is not professional advice. Your optional name stays in the browser. The application does not persist birth submissions or reports. See our <a href="/privacy">Privacy Policy</a> for provider processing details.</p>
    </div></div>
  </article>;
}
